### ISSUE TITLE
Notification in Discord

### ISSUE THREAD

**Issue by HippyCraig** [Fair-Strides/FVTT-Custom-Journal-Theming#1]
It looks like you posted the following:

> Custom Journal Please note that, as this is written, I am no longer maintaining this, and have not for a while. Whoever feels like forking the repo and toying with it is more than welcome to do so. I haven't found how to remove/deprecate this beyond the versioning already outdated,…

It might help others if you put that at the top of the readme file, Red and Bolded its not clear from this site that you’re not maintaining it any longer.  

Its a shame that you wont be updating it as its a nice module, but hopefully someone picks it up and continues it, I myself am not a java programmer so I can’t volunteer.

**Comment by Fair-Strides** [comment]
Ahh. That was from the original author. I had forgotten to remove that in all the updates...
