### ISSUE TITLE
Warnings and errors in console

### ISSUE THREAD

**Issue by ianm32** [Fair-Strides/FVTT-Custom-Journal-Theming#2]
While loading Foundry and watching the console, I noticed that there are a number of them that look like they involve Custom Journal's font loading.  It's possible that it's interacting with the [Custom Fonts](https://github.com/arcanistzed/custom-fonts)  module in some way.  I don't notice any real difference to functionality in Foundry, but I thought sharing these might be worthwhile.
![11](https://user-images.githubusercontent.com/27756065/149444604-5351edde-5c93-4538-8fcd-8813e747cca5.JPG)
![1](https://user-images.githubusercontent.com/27756065/149444612-25db5abb-dc95-4686-b57b-c1b80e184fa5.JPG)

**Comment by ErroneousBosch** [comment]
I am seeing a similar warning in Chrome:

```
Failed to decode downloaded font: https://foundryvtt.twilightrose.space/modules/custom-journal/fonts/loversquarrel-regular.woff2
game:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
game:1 Failed to decode downloaded font: https://foundryvtt.twilightrose.space/modules/custom-journal/fonts/loversquarrel-regular.woff
game:1 OTS parsing error: incorrect file size in WOFF header
```

You may want to consider loading fonts via Google Fonts CSS include rather than including  in the module:

`@import url('https://fonts.googleapis.com/css?family=Lovers%20Quarrel&display=swap');`

https://www.w3docs.com/snippets/css/how-to-import-google-fonts-in-css-file.html

**Comment by Fair-Strides** [comment]
> 

I have attempted to incorporate this in several of the style sheets. I don't think Foundry is liking it:
`@import url('https://fonts.googleapis.com/css?family=Lovers%20Quarrel&display=swap');
@import url('https://fonts.googleapis.com/css?family=Play&display=swap');`

![image](https://user-images.githubusercontent.com/72034470/154592667-01bcbbec-418c-4ac6-b43b-527a8e75e8bc.png)

**Comment by Fair-Strides** [comment]
In the update to v10, I've re-worked the font selection to use google imports properly. The only pre-packaged font now is the AngloText because it was not a google font.
