### ISSUE TITLE
Settings and image cannot  be edited  after update

### ISSUE THREAD

**Issue by Elio-87** [Fair-Strides/FVTT-Custom-Journal-Theming#4]
After I choose update all ; monks enhanced journal seems to interfeer with this now. 
I am unable to see teh core custom image you get when you " start" a image sheet.
And the settings  button become bugged; after I changed it to that style, but it stiill looks likea normal journal with a image and error text box, where the image part is unable to be edited. 

Not sure what happened with the update to affect it like this.

**Comment by Fair-Strides** [comment]
Unfortunately, the v10 update introduced a Journals 2.0 system that is harder to work with. I've updated the normal journal styles, but I've had to drop the Custom Image and Custom Video styles I'm afraid.
