### ISSUE TITLE
v11 install

### ISSUE THREAD

**Issue by rafacrudi** [Fair-Strides/FVTT-Custom-Journal-Theming#5]
Was the last update for v10 or v11?

Trying to update on v11.304, having this error:

Error: Unable to load valid module manifest data from "https://github.com/Fair-Strides/FVTT-Custom-Journal-Theming/blob/v10-journals/module.json"
Error parsing module manifest data from https://github.com/Fair-Strides/FVTT-Custom-Journal-Theming/blob/v10-journals/module.json: Unexpected token '<', "

<!DOCTYPE "... is not valid JSON
    at Module.installPackage (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:1692)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async SetupView.handlePost (file:///C:/Program%20Files/Foundry%20Virtual%20Tabletop/resources/app/dist/server/views/setup.mjs:1:2076)
fetch @ foundry.js:67853

**Comment by Fair-Strides** [comment]
Please note the "v10-journals" part in the link. This is a v10 version for now.

Once PF1E updates to v11, I'll be switching my stuff over to v11 as well.

**Comment by n3riii** [comment]
I get the same error even though I am still on v10. Uninstalling the module and trying to re-install it ended in the same error.

**Comment by Fair-Strides** [comment]
> I get the same error even though I am still on v10. Uninstalling the module and trying to re-install it ended in the same error.

Ahh, I see. I need to track down where the bad link is, but it's pointing to "view the processed file" instead of getting the raw file.

You want this:
https://raw.githubusercontent.com/Fair-Strides/FVTT-Custom-Journal-Theming/v10-journals/module.json
